<?php

/**
 * Copyright © 2016 Magento. All rights reserved.
 * See COPYING.txt for license details.
 */

use Magento\Framework\App\Action\Action;

// @codingStandardsIgnoreFile
?>
<?php
/**
 * Product list template
 *
 * @var $block \Magento\Catalog\Block\Product\ListProduct
 */
?>
<?php
$_productCollection = $block->getLoadedProductCollection();
$_helper = $this->helper('Magento\Catalog\Helper\Output');
$shopkartliteHelper = $this->helper('Hidden\ShopkartLite\Helper\Data');
$showNewLabel = $shopkartliteHelper->getConfigValue('shopkartlitesettings/category_settings/show_new_label');
$showSaleLabel = $shopkartliteHelper->getConfigValue('shopkartlitesettings/category_settings/show_sale_label');
$showBorder = $shopkartliteHelper->getConfigValue('shopkartlitesettings/category_settings/show_border');
?>
<?php if (!$_productCollection->count()) : ?>
    <div class="message info empty">
        <div><?php /* @escapeNotVerified */ echo __('We can\'t find products matching the selection.') ?></div>
    </div>
<?php else : ?>
    <?php echo $block->getToolbarHtml() ?>
    <?php echo $block->getAdditionalHtml() ?>
    <?php
    if ($block->getMode() == 'grid') {
        $viewMode = 'grid';
        $image = 'category_page_grid';
        $showDescription = false;
        $templateType = \Magento\Catalog\Block\Product\ReviewRendererInterface::SHORT_VIEW;
    } else {
        $viewMode = 'list';
        $image = 'category_page_list';
        $showDescription = true;
        $templateType = \Magento\Catalog\Block\Product\ReviewRendererInterface::FULL_VIEW;
    }
    /**
     * Position for actions regarding image size changing in vde if needed
     */
    $pos = $block->getPositioned();
    ?>

    <style>
        .productlist-card-item {
            width: calc(25% - 13px);
            padding: 10px 5px;
            display: inline-block;
            margin-bottom: 20px;
        }

        .toolbar .modes {
            display: none !important;
        }

        @media only screen and (min-width : 768px) {
            .page-layout-2columns-left .column.main {
                width: 78%;
            }

            .page-layout-2columns-left .sidebar-additional,
            .page-layout-2columns-left .sidebar-main {
                width: 22%;
            }
        }

        @media only screen and (min-width : 1360px) and (max-width : 1366px) {

            .product-card,
            .product-front,
            .product-card.animate,
            .make-3D-space {
                height: 375px;
            }
        }
    </style>

    <script>
        require([
            'jquery',
            'mage/translate',
            'mageplaza/core/owl.carousel'
        ], function($, $t) {
            jQuery(window).ready(function() {

                // Lift card and show stats on Mouseover
                jQuery('.product-card').hover(function() {
                    jQuery(this).addClass('animate');
                    jQuery('div.carouselNext, div.carouselPrev').addClass('visible');
                }, function() {
                    jQuery(this).removeClass('animate');
                    jQuery('div.carouselNext, div.carouselPrev').removeClass('visible');
                });


                /* ----  Image Gallery Carousel   ---- */

                var carousel = jQuery('.carousel ul');
                var carouselSlideWidth = 335;
                var carouselWidth = 0;
                var isAnimating = false;

                // building the width of the casousel
                jQuery('.carousel li').each(function() {
                    carouselWidth += carouselSlideWidth;
                });
                jQuery(carousel).css('width', carouselWidth);

                // Load Next Image
                jQuery('div.carouselNext').on('click', function() {
                    var currentLeft = Math.abs(parseInt(jQuery(carousel).css("left")));
                    var newLeft = currentLeft + carouselSlideWidth;
                    if (newLeft == carouselWidth || isAnimating === true) {
                        return;
                    }
                    jQuery('.carousel ul').css({
                        'left': "-" + newLeft + "px",
                        "transition": "300ms ease-out"
                    });
                    isAnimating = true;
                    setTimeout(function() {
                        isAnimating = false;
                    }, 300);
                });

                // Load Previous Image
                jQuery('div.carouselPrev').on('click', function() {
                    var currentLeft = Math.abs(parseInt(jQuery(carousel).css("left")));
                    var newLeft = currentLeft - carouselSlideWidth;
                    if (newLeft < 0 || isAnimating === true) {
                        return;
                    }
                    jQuery('.carousel ul').css({
                        'left': "-" + newLeft + "px",
                        "transition": "300ms ease-out"
                    });
                    isAnimating = true;
                    setTimeout(function() {
                        isAnimating = false;
                    }, 300);
                });
            })
        });

        function mnnAddQty(product_id) {
            qtd = parseInt(jQuery('.product-' + product_id).find('.qtd-addtocart').val());
            if (qtd < 999) {
                qtd_atual = qtd + 1;
                jQuery('.product-' + product_id).find('.qtd-addtocart').val(qtd_atual);
                jQuery('.m2n-num2add-' + product_id).html(qtd_atual + ' ');

                peso_unidade = jQuery('.product-' + product_id).find('.weight-qtd input').val();
                jQuery('.product-' + product_id).find('.weight-qtd .qtd-selected').html(qtd_atual * peso_unidade);
            }
        }

        function mnnRemoveQty(product_id) {
            qtd = parseInt(jQuery('.product-' + product_id).find('.qtd-addtocart').val());
            if (qtd > 1) {
                qtd_atual = qtd - 1;
                jQuery('.product-' + product_id).find('.qtd-addtocart').val(qtd_atual);
                jQuery('.m2n-num2add-' + product_id).html(qtd_atual + ' ');

                peso_unidade = jQuery('.product-' + product_id).find('.weight-qtd input').val();
                jQuery('.product-' + product_id).find('.weight-qtd .qtd-selected').html(qtd_atual * peso_unidade);
            }
        }

        function mnnAddToWishlist(product_id) {
            jQuery('.product-' + product_id).find('.loading').css('display', 'flex');
            jQuery('.product-' + product_id).find('.add-success').hide();
            jQuery('.product-' + product_id).find('.add-fail').hide();

            jQuery.post("<?= $block->getUrl("adicionarcarrinho/index/savewishlist"); ?>", {
                    product_id: product_id
                },
                function(data) {
                    jQuery('.product-' + product_id).find('.loading').hide();
                    if (data == '1') {
                        jQuery('.product-' + product_id).find('.add-success').css('display', 'flex');
                    } else {
                        jQuery('.product-' + product_id).find('.add-fail').css('display', 'flex');
                        jQuery('.product-' + product_id).find('.add-fail span').hide();
                        jQuery('.product-' + product_id).find('.add-fail .wishlist-error-msg').show();
                    }

                    setTimeout(function() {
                        jQuery('.product-' + product_id).find('.add-success').hide();
                        jQuery('.product-' + product_id).find('.add-fail').hide();
                        jQuery('.product-' + product_id).find('.add-fail span').show();
                        jQuery('.product-' + product_id).find('.add-fail .wishlist-error-msg').hide();
                    }, 1500);
                }
            )
        }

        function mnnAddToCart(product_id) {
            qtd = parseInt(jQuery('.product-' + product_id).find('.qtd-addtocart').val());
            qtdInCart = parseInt(jQuery('.product-' + product_id).find('.cart-check-qtd').html());

            jQuery('.product-' + product_id).find('.loading').css('display', 'flex');
            jQuery('.product-' + product_id).find('.add-success').hide();
            jQuery('.product-' + product_id).find('.add-fail').hide();

            if (qtdInCart > 0) {
                jQuery.post("<?= $block->getUrl("adicionarcarrinho/index/update"); ?>", {
                        product_id: product_id,
                        qtd: qtd
                    },
                    function(data) {
                        jQuery('.product-' + product_id).find('.loading').hide();
                        if (data == '1') {
                            jQuery('.product-' + product_id).find('.cart-check-qtd').html(parseInt(qtd));
                            mnnAlert("Adicionado ao Carrinho", "Quantidade do produto atualizada", "success");
                        } else {
                            mnnAlert("Não foi possível atualizar", "Produto/quantidade do produto indisponível", "error");
                        }
                    }
                )
            } else {
                jQuery.post("<?= $block->getUrl("adicionarcarrinho/index/save"); ?>", {
                        product_id: product_id,
                        qtd: qtd
                    },
                    function(data) {
                        jQuery('.product-' + product_id).find('.loading').hide();
                        if (data == '1') {
                            jQuery('.product-' + product_id).find('.cart-check-qtd').html(parseInt(qtd));
                            mnnAlert("Adicionado ao Carrinho", "Produto adicionado com sucesso", "success");
                        } else {
                            mnnAlert("Não foi possível adicionar", "Produto/quantidade do produto indisponível", "error");
                        }
                    }
                )
            }
        }
    </script>

    <div class="mnn-product-list productlist">
        <?php
        foreach ($_productCollection as $_item) {
            $objectManager = \Magento\Framework\App\ObjectManager::getInstance();
            $_product = $objectManager->get('Magento\Catalog\Api\ProductRepositoryInterface')->getById($_item->getId());

            $__cart = $objectManager->get('\Magento\Checkout\Model\Session')->getQuote();
            $__result = $__cart->getAllVisibleItems();
            $__itemsIds = array();
            foreach ($__result as $__cartItem) {
                array_push($__itemsIds, $__cartItem->getProduct()->getId());
            }

            $image = 'new_products_content_widget_grid';
            $productImage = $block->getImage($_product, $image);
        ?>
            <div class="productlist-card-item">
                <div class="make-3D-space">
                    <div class="product-card product-<?= $_product->getId() ?>">
                        <div class="mnn-card-loading">
                            <i class="fa fa-circle-o-notch fa-spin fa-3x fa-fw"></i>
                        </div>
                        <div class="product-front">
                            <div class="shadow"></div>

                            <?php echo $productImage->toHtml(); ?>

                            <div class="image_overlay"></div>
                            <a href="<?= $_product->getProductUrl() ?>" class="view_details">Ver Produto</a>
                            <div class="stats">
                                <div class="stats-container">
                                    <span class="product_price">
                                        <?php
                                        $weight = "";
                                        if ($_product->getProdutoPorPeso()) {
                                            if ($_product->getSpecialPrice()) {
                                                $_oldprice = ($_product->getPrice() * 1000) / $_product->getProdutoPesoUnidade();
                                                $_price = ($_product->getSpecialPrice() * 1000) / $_product->getProdutoPesoUnidade();
                                        ?>
                                                <div class="old-price">
                                                    <?= 'R$' . number_format($_oldprice, 2, ',', '.') . $weight ?>
                                                </div>
                                                <div>
                                                    <?= 'R$' . number_format($_price, 2, ',', '.') . '/kg' ?>
                                                </div>
                                            <?php
                                            } else {
                                                $_price = ($_product->getPrice() * 1000) / $_product->getProdutoPesoUnidade();
                                            ?>
                                                <div>
                                                    <?= 'R$' . number_format($_price, 2, ',', '.') . '/kg' ?>
                                                </div>
                                            <?php
                                            }
                                        } else {
                                            if (($_product->getSpecialPrice() < $_product->getPrice()) && $_product->getSpecialPrice()) {
                                            ?>
                                                <div class="old-price">
                                                    <?= 'R$' . number_format($_product->getPrice(), 2, ',', '.') . $weight ?>
                                                </div>
                                                <div>
                                                    <?= 'R$' . number_format($_product->getSpecialPrice(), 2, ',', '.') . $weight ?>
                                                </div>
                                        <?php
                                            } else {
                                                echo 'R$' . number_format($_product->getPrice(), 2, ',', '.') . $weight;
                                            }
                                        }
                                        ?>
                                    </span>
                                    <span class="product_name"><?= $_product->getName() ?></span>
                                    <p>
                                        <?php
                                        $categories = $_product->getCategoryIds();
                                        foreach ($categories as $category) {
                                            $cat = $objectManager->create('Magento\Catalog\Model\Category')->load($category);
                                            $_category_name = $cat->getName();
                                        }
                                        echo $_category_name;
                                        ?>
                                    </p>

                                    <div class="product-more-info">
                                        <div class="product-info-price">
                                            <?php
                                            $weight = "/unidade";

                                            if ($_product->getProdutoPorPeso()) {
                                                $weight = '/<span style="font-size: 12px;">' . $_product->getProdutoPesoUnidade() . $_product->getProdutoUnidadeMedida() . '</span>';
                                            }

                                            if ($_product->getSpecialPrice()) {
                                                echo 'R$' . number_format($_product->getSpecialPrice(), 2, ',', '.') . $weight;
                                            } else {
                                                echo 'R$' . number_format($_product->getPrice(), 2, ',', '.') . $weight;
                                            }
                                            ?>
                                        </div>

                                        <?php
                                        $_product_qty = 0;

                                        if (in_array($_product->getId(), $__itemsIds)) {
                                            $cart = $this->helper('\Magento\Checkout\Helper\Cart');
                                            $itens = $cart->getQuote()->getItems();

                                            foreach ($itens as $item) {
                                                if ($_product->getId() == $item->getProduct_id()) {
                                                    $_product_qty = $item->getQty();
                                                }
                                            }
                                        }
                                        if (!$_product->getProdutoPorPeso()) {
                                        ?>
                                            <div class="img-hover-cart cart-check-<?= $_product->getId() ?>">
                                                <span class="cart-check-qtd"><?= $_product_qty ?></span> <span>no Carrinho</span>
                                            </div>
                                        <?php
                                        } else {
                                            if ($_product_qty == 0) {
                                                $qty_weight = 1;
                                            } else {
                                                $qty_weight = $_product_qty;
                                            }
                                        ?>
                                            <div class="weight-qtd">
                                                <span class="qtd-selected"><?= ($_product->getProdutoPesoUnidade() * $qty_weight) ?></span>g
                                                <input value="<?= $_product->getProdutoPesoUnidade() ?>" type="hidden">
                                                <span style="display: none" class="cart-check-qtd"><?= $_product_qty ?></span>
                                            </div>
                                        <?php
                                        }
                                        ?>
                                    </div>

                                    <div class="product-options">
                                        <div class="product-options-item">
                                            <button type="button" onclick="mnnRemoveQty(<?= $_product->getId() ?>);">
                                                <svg xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink" aria-hidden="true" focusable="false" width="1em" height="1em" style="-ms-transform: rotate(360deg); -webkit-transform: rotate(360deg); transform: rotate(360deg);" preserveAspectRatio="xMidYMid meet" viewBox="0 0 24 24">
                                                    <g fill="none" stroke="#626262" stroke-width="2" stroke-linecap="round" stroke-linejoin="round">
                                                        <path d="M5 12h14" />
                                                    </g>
                                                </svg>
                                            </button>
                                        </div>
                                        <div class="product-options-item">
                                            <input class="qtd-addtocart" type="number" min="1" value="<?= $_product_qty > 1 ? $_product_qty : '1' ?>" readonly="readonly" type="number" min="0" max="999">
                                        </div>
                                        <div class="product-options-item">
                                            <button type="button" onclick="mnnAddQty(<?= $_product->getId() ?>);">
                                                <svg xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink" aria-hidden="true" focusable="false" width="1em" height="1em" style="-ms-transform: rotate(360deg); -webkit-transform: rotate(360deg); transform: rotate(360deg);" preserveAspectRatio="xMidYMid meet" viewBox="0 0 24 24">
                                                    <g fill="none" stroke="#626262" stroke-width="2" stroke-linecap="round" stroke-linejoin="round">
                                                        <path d="M12 5v14" />
                                                        <path d="M5 12h14" />
                                                    </g>
                                                </svg>
                                            </button>
                                        </div>
                                        <div class="product-options-item">
                                            <button type="button" onclick="mnnAddToCart(<?= $_product->getId() ?>)">
                                                <svg xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink" aria-hidden="true" focusable="false" width="1em" height="1em" style="-ms-transform: rotate(360deg); -webkit-transform: rotate(360deg); transform: rotate(360deg);" preserveAspectRatio="xMidYMid meet" viewBox="0 0 24 24">
                                                    <g fill="none" stroke="#fff" stroke-width="2" stroke-linecap="round" stroke-linejoin="round">
                                                        <circle cx="9" cy="21" r="1" />
                                                        <circle cx="20" cy="21" r="1" />
                                                        <path d="M1 1h4l2.68 13.39a2 2 0 0 0 2 1.61h9.72a2 2 0 0 0 2-1.61L23 6H6" />
                                                    </g>
                                                </svg>
                                            </button>
                                        </div>
                                    </div>
                                </div>
                            </div>
                        </div>
                        <div class="product-back">
                            <div class="shadow"></div>
                            <div class="carousel">
                                <ul>
                                    <li><img src="https://s3-us-west-2.amazonaws.com/s.cdpn.io/245657/t-shirt-large.png" alt="" /></li>
                                    <li><img src="https://s3-us-west-2.amazonaws.com/s.cdpn.io/245657/t-shirt-large2.png" alt="" /></li>
                                    <li><img src="https://s3-us-west-2.amazonaws.com/s.cdpn.io/245657/t-shirt-large3.png" alt="" /></li>
                                </ul>
                                <div class="arrows-perspective">
                                    <div class="carouselPrev">
                                        <div class="y"></div>
                                        <div class="x"></div>
                                    </div>
                                    <div class="carouselNext">
                                        <div class="y"></div>
                                        <div class="x"></div>
                                    </div>
                                </div>
                            </div>
                            <div class="flip-back">
                                <div class="cy"></div>
                                <div class="cx"></div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        <?php
        }
        ?>
    </div>
    <?php echo $block->getToolbarHtml() ?>
    <?php if (!$block->isRedirectToCartEnabled()) : ?>
        <script type="text/x-magento-init">
            {
            "[data-role=tocart-form], .form.map.checkout": {
            "catalogAddToCart": {}
            }
            }
        </script>
    <?php endif; ?>
<?php endif; ?>