<style>
    #subcategory {
        width: 350px;
        height: 100%;
        position: fixed;
        left: 430px;
        top: 0;
        display: inline-block;
        background: #f6f6f6;
        border-left: 1px solid #e9e9e9;
        z-index: 99999999;
        padding: 15px;
    }

    #menu {
        width: 430px;
        height: 100%;
        position: fixed;
        left: 0;
        top: 0;
        display: inline-block;
        background: #fff;
        z-index: 99999999;
        padding: 0;
    }

    .menu_list {
        width: 400px;
        display: inline-flex;
        margin-bottom: 10px;
        padding: 15px;
        padding-top: 25px;
        background: #fff;
    }

    .menu_list .menu_item {
        width: 100px;
        margin: auto;
        text-align: center;
        color: #626262;
    }

    .menu_list .menu_item svg {
        font-size: 25px;
    }

    .menu_list .menu_item .menu_title {
        font-size: 15px;
    }

    .menu_logo {
        width: 400px;
        height: 70px;
        padding: 15px;
    }

    .menu_logo img {
        width: auto;
        max-width: 200px;
        max-height: 60px;
        margin: auto;
        display: block;
    }

    .category_list {
        height: calc(100% - 175px);
        overflow-y: auto;
        overflow-x: none;
        margin-top: 10px;
        padding: 15px;
        background: #fff;
    }

    .category_list .category_item {
        width: 100%;
        padding: 10px;
        display: inline-flex;
    }

    .category_list .category_item span {
        width: calc(100% - 40px)
    }

    .category_list .category_item div {
        width: 40px;
        cursor: pointer;
    }

    .category_list .category_item div svg {
        font-size: 18px;
    }

    .category_list .category_item a {
        color: #666;
        width: 100%;
        display: block;
        font-size: 15px;
    }

    .category_title {
        display: inline-flex;
        padding-left: 7px;
        margin-bottom: 10px;
    }

    .category_title .icon {
        width: 30px;
    }

    .category_title .icon svg {
        font-size: 20px;
    }

    .category_title .title {
        width: calc(100% - 30px);
    }

    .category_title .title a {
        color: #666;
        font-weight: 600;
        font-size: 16px;
    }

    .category_list::-webkit-scrollbar {
        width: 9px;
        height: 9px;
    }

    .category_list::-webkit-scrollbar-thumb {
        background: linear-gradient(13deg, #48cfad 14%, #48cfad 64%);
        border-radius: 10px;
    }

    .category_list::-webkit-scrollbar-thumb:hover {
        background: linear-gradient(13deg, #48cfad 14%, #48cfad 64%);
    }

    .category_list::-webkit-scrollbar-track {
        background: #eee;
        border-radius: 10px;
    }

    #subcategory,
    #subcategory .category_children {
        display: none;
    }

    .subcategory_item {
        padding: 8px 10px;
        width: 100%;
    }

    .subcategory_item a {
        color: #666;
    }

    #mnn_menu {
        position: fixed;
        z-index: 99999999;
        background: rgba(0, 0, 0, 0.35);
        width: 100%;
        height: 100%;
        left: 0;
        top: 0;
        display: none;
    }

    .page-wrapper .page-header .header.content .block-search .field.search .control .input-text {
        border-radius: 100px;
        border: none;
    }

    @media only screen and (max-width : 480px) {
        #menu {
            width: 90%;
        }

        .menu_list,
        .menu_logo {
            width: calc(100% - 30px);
        }
    }
</style>










<?php

/**
 * Copyright © 2016 Magento. All rights reserved.
 * See COPYING.txt for license details.
 */
// @codingStandardsIgnoreFile
?>
<?php
/**
 * Top menu for store
 *
 * @see \Magento\Theme\Block\Html\Topmenu
 */
?>
<?php $columnsLimit = $block->getColumnsLimit() ?: 0; ?>
<?php $_menu = $block->getHtml('level-top', 'submenu', $columnsLimit) ?>
<?php
$helper = $this->helper('Hidden\ShopkartLite\Helper\Data');
$baseUrl = $helper->getBaseUrl();
$ishome = $helper->getIsHome();

$showHome = $helper->getConfigValue('shopkartlitesettings/navigation_settings/enable');
?>

<style>
    .navigation span {
        font-weight: 400;
    }

    .navigation .nav-5 {
        float: right;
    }

    .navigation .nav-1 {
        margin-right: 20px;
    }

    .navigation .nav-1 span {
        font-weight: 500;
    }

    .nav-sections,
    .nav-sections-item-content,
    .nav-sections-item-content .ui-menu,
    .nav-sections-item-content .ui-menu li {
        height: 43px !important;
    }

    .nav-sections-item-content .ui-menu li a {
        height: 40px !important;
    }

    .nav-sections .navigation>ul>li.level0>a.level-top {
        font-size: 16px;
        margin-top: -2px;
        background: transparent !important
    }

    .nav-sections-item-content .ui-menu li a span {
        text-transform: initial;
    }

    .navigation .level0>.level-top {
        line-height: 12px;
        cursor: pointer;
    }
</style>

<nav class="navigation" role="navigation">
    <ul id="ui-id-1" class="ui-menu ui-widget ui-widget-content ui-corner-all" role="menu" tabindex="0" aria-activedescendant="ui-id-2">
        <li onclick="showCategoryMenu()" class="level0 nav-1 category-item first level-top ui-menu-item" role="presentation">
            <a class="level-top ui-corner-all" id="ui-id-2" tabindex="-1" role="menuitem">
                <i class="fa fa-bars" aria-hidden="true"></i>
                <span>Departamentos</span>
            </a>
        </li>

        <li class="level0 nav-2 category-item first level-top ui-menu-item" role="presentation">
            <a href="/" class="level-top ui-corner-all" id="ui-id-2" tabindex="-1" role="menuitem">
                <span>Início</span>
            </a>
        </li>
        <li class="level0 nav-3 category-item first level-top ui-menu-item" role="presentation">
            <a href="/wishlist" class="level-top ui-corner-all" id="ui-id-2" tabindex="-1" role="menuitem">
                <span>Lista de Compras</span>
            </a>
        </li>
        <li class="level0 nav-4 category-item first level-top ui-menu-item" role="presentation">
            <a href="/contact" class="level-top ui-corner-all" id="ui-id-2" tabindex="-1" role="menuitem">
                <span>Fale Conosco</span>
            </a>
        </li>
    </ul>
</nav>

<?php
$objectManager = \Magento\Framework\App\ObjectManager::getInstance();
$request = $objectManager->get('Magento\Framework\App\Action\Context')->getRequest();
if ($request->getFullActionName() == 'cms_index_index') {

?>
    <div class="mnn-categories-slider owl-carousel owl-theme">
        <?php
        $objectManager =  \Magento\Framework\App\ObjectManager::getInstance();
        $categoryCollection = $objectManager->get('\Magento\Catalog\Model\ResourceModel\Category\CollectionFactory');
        $categories = $categoryCollection->create();
        $categories->addAttributeToSelect('*');
        $categories->addAttributeToFilter('entity_id', array('gt' => 2));
        $categories->addAttributeToFilter('level', 2);
        $categories->addAttributeToFilter('is_active', 1);
        $categories->setOrder('name', 'ASC');

        foreach ($categories as $_category) {
            $collectionFactory = $objectManager->get('\Magento\Catalog\Model\ResourceModel\Product\CollectionFactory')->create();
            $products = $collectionFactory->addAttributeToSelect('external_image')
                ->addCategoriesFilter(['in' => $_category->getId()])
                ->setPageSize(4);

            $products->getSelect()->orderRand();

            $products = $products->getItems();

        ?>
            <div>
                <a href="<?= $_category->getUrl() ?>">
                    <div class="slider-category_item">
                        <?= $_category->getDescription() ?>
                        <span><?= $_category->getName() ?></span>
                    </div>
                </a>
            </div>
        <?php
        }
        ?>
    </div>
<?php
}
?>

<style>
    .slider-category_name {
        padding: 0 5px;
        font-size: 13px;
        color: #555;
        -webkit-line-clamp: 1;
        display: -webkit-box;
        -webkit-box-orient: vertical;
        overflow: hidden;
        margin-top: -3px;
    }

    .slider-category_item {
        width: 110px;
        height: 110px;
        display: inline-block;
        background: #fcfcfc;
        margin: 5px;
        padding: 5px;
        margin-right: 5px;
        border-radius: 3px;
        text-align: center;
        border: 1px solid #ddd;
    }

    .slider-category_item svg {
        font-size: 40px;
        display: block;
        margin: auto;
        margin-top: 26px;
    }

    .slider-category_item span {
        font-size: 12px;
        color: #626262;
        -webkit-line-clamp: 1;
        display: -webkit-box;
        -webkit-box-orient: vertical;
        overflow: hidden;
        margin-top: 5px;
    }

    .mnn-categories-slider .owl-dots {
        display: none;
    }

    .mnn-categories-slider {
        padding: 15px 0;
        display: none !important;
    }

    @media only screen and (max-width : 480px) {
        .mnn-categories-slider {
            display: block !important;
        }
    }
</style>

<script>
    require([
        'jquery',
        'mage/translate',
        'mageplaza/core/owl.carousel'
    ], function($, $t) {
        jQuery(window).ready(function() {
            jQuery('.mnn-categories-slider').owlCarousel({
                loop: true,
                responsiveClass: true,
                autoplay: false,
                autoplayTimeout: 8000,
                responsive: {
                    0: {
                        items: 3,
                        nav: true,
                        autoplay: false,
                    }
                }
            })
        })
    })
</script>

<style>
    .mnn-menu-mobile {
        display: none;
    }

    @media only screen and (max-width : 480px) {
        .mnn-menu-mobile {
            display: inline-block;
            position: fixed;
            background: rgba(60, 60, 60, 0.9);
            left: 0;
            bottom: 0;
            width: 100%;
            height: 46px;
            z-index: 9999999999999;
        }

        .mnn-menu-mobile .mnn-menu {
            width: 100%;
            display: inline-flex;
            height: 100%;
        }

        .mnn-menu .mnn-menu_item {
            width: 20%;
            text-align: center;
            height: 100%;
        }

        .mnn-menu .mnn-menu_item svg {
            font-size: 21px;
            margin-top: 3px;
            width: 100%;
            padding: 10px 0;
        }

        .menu_item_check {
            width: calc(20% - 10px);
            height: 0px;
            background: #48cfad;
            position: absolute;
            z-index: 9999999999999;
            display: block;
            margin: auto;
            margin-left: 5px;
            border-bottom-left-radius: 4px;
            border-bottom-right-radius: 4px;
            opacity: 0;
            transition: 0.2s;
        }

        .mnn-menu_item .active {
            height: 4px;
            opacity: 1;
            transition: 0.2s;
        }

        .category_list {
            height: calc(100% - 272px) !important;
            overflow-x: hidden;
        }
    }
</style>

<div class="mnn-menu-mobile">
    <div class="mnn-menu">
        <div onclick="selectMenu('home')" class="mnn-menu_item menu-mobile-home">
            <div class="menu_item_check">
            </div>
            <a href="/">
                <svg xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink" aria-hidden="true" focusable="false" width="1em" height="1em" style="-ms-transform: rotate(360deg); -webkit-transform: rotate(360deg); transform: rotate(360deg);" preserveAspectRatio="xMidYMid meet" viewBox="0 0 24 24">
                    <g fill="none" stroke="#fff" stroke-width="2" stroke-linecap="round" stroke-linejoin="round">
                        <path d="M3 9l9-7l9 7v11a2 2 0 0 1-2 2H5a2 2 0 0 1-2-2z" />
                        <path d="M9 22V12h6v10" />
                    </g>
                </svg>
            </a>
        </div>
        <div onclick="selectMenu('cart')" class="mnn-menu_item menu-mobile-cart">
            <div class="menu_item_check">
            </div>
            <a href="/checkout/cart/">
                <svg xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink" aria-hidden="true" focusable="false" width="1em" height="1em" style="-ms-transform: rotate(360deg); -webkit-transform: rotate(360deg); transform: rotate(360deg);" preserveAspectRatio="xMidYMid meet" viewBox="0 0 24 24">
                    <g fill="none" stroke="#fff" stroke-width="2" stroke-linecap="round" stroke-linejoin="round">
                        <circle cx="9" cy="21" r="1" />
                        <circle cx="20" cy="21" r="1" />
                        <path d="M1 1h4l2.68 13.39a2 2 0 0 0 2 1.61h9.72a2 2 0 0 0 2-1.61L23 6H6" />
                    </g>
                </svg>
            </a>
        </div>
        <div onclick="showChangeStore()" class="mnn-menu_item menu-mobile-store">
            <div class="menu_item_check">
            </div>
            <svg xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink" aria-hidden="true" focusable="false" width="1em" height="1em" style="-ms-transform: rotate(360deg); -webkit-transform: rotate(360deg); transform: rotate(360deg);" preserveAspectRatio="xMidYMid meet" viewBox="0 0 24 24">
                <g fill="none" stroke="#fff" stroke-width="2" stroke-linecap="round" stroke-linejoin="round">
                    <path d="M21 10c0 7-9 13-9 13s-9-6-9-13a9 9 0 0 1 18 0z" />
                    <circle cx="12" cy="10" r="3" />
                </g>
            </svg>
        </div>
        <div onclick="selectMenu('wishlist')" class="mnn-menu_item menu-mobile-wishlist">
            <div class="menu_item_check">
            </div>
            <a href="/wishlist">
                <svg xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink" aria-hidden="true" focusable="false" width="1em" height="1em" style="-ms-transform: rotate(360deg); -webkit-transform: rotate(360deg); transform: rotate(360deg);" preserveAspectRatio="xMidYMid meet" viewBox="0 0 24 24">
                    <g fill="none" stroke="#fff" stroke-width="2" stroke-linecap="round" stroke-linejoin="round">
                        <path d="M9 11l3 3L22 4" />
                        <path d="M21 12v7a2 2 0 0 1-2 2H5a2 2 0 0 1-2-2V5a2 2 0 0 1 2-2h11" />
                    </g>
                </svg>
            </a>
        </div>
        <div onclick="selectMenu('account')" class="mnn-menu_item menu-mobile-account">
            <div class="menu_item_check">
            </div>
            <a href="/customer/account/">
                <svg xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink" aria-hidden="true" focusable="false" width="1em" height="1em" style="-ms-transform: rotate(360deg); -webkit-transform: rotate(360deg); transform: rotate(360deg);" preserveAspectRatio="xMidYMid meet" viewBox="0 0 24 24">
                    <g fill="none" stroke="#fff" stroke-width="2" stroke-linecap="round" stroke-linejoin="round">
                        <path d="M20 21v-2a4 4 0 0 0-4-4H8a4 4 0 0 0-4 4v2" />
                        <circle cx="12" cy="7" r="4" />
                    </g>
                </svg>
            </a>
        </div>

        <script>
            function selectMenu(menu_selected) {
                jQuery('.menu_item_check').removeClass('active');
                jQuery('.menu-mobile-' + menu_selected).find('.menu_item_check').addClass('active');
            }

            <?php
            $url_active = $_SERVER['REQUEST_URI'];

            if ($url_active != "") {
            ?>
                require([
                    'jquery'
                ], function($, $t) {
                    jQuery(document).ready(function() {
                        url = "<?= $url_active ?>";

                        if (url.toLowerCase().indexOf("customer") >= 0) {
                            menu = 'account';
                        } else if (url.toLowerCase().indexOf("wishlist") >= 0) {
                            menu = 'wishlist';
                        } else if (url.toLowerCase().indexOf("checkout") >= 0) {
                            menu = 'cart';
                        } else {
                            menu = 'home';
                        }

                        selectMenu(menu)
                    })
                })
            <?php
            }
            ?>
        </script>

    </div>
</div>