<style>
    #subcategory {
        width: 350px;
        height: 100%;
        position: fixed;
        left: 430px;
        top: 0;
        display: inline-block;
        background: #f6f6f6;
        border-left: 1px solid #e9e9e9;
        z-index: 99999999;
        padding: 15px;
    }

    #menu {
        width: 430px;
        height: 100%;
        position: fixed;
        left: 0;
        top: 0;
        display: inline-block;
        background: #fff;
        z-index: 99999999;
        padding: 0;
    }

    .menu_list {
        width: 400px;
        display: inline-flex;
        margin-bottom: 10px;
        padding: 15px;
        padding-top: 25px;
        background: #fff;
    }

    .menu_list .menu_item {
        width: 100px;
        margin: auto;
        text-align: center;
        color: #626262;
    }

    .menu_list .menu_item svg {
        font-size: 25px;
    }

    .menu_list .menu_item .menu_title {
        font-size: 15px;
    }

    .menu_logo {
        width: 400px;
        height: 70px;
        padding: 15px;
    }

    .menu_logo img {
        width: auto;
        max-width: 200px;
        max-height: 60px;
        margin: auto;
        display: block;
    }

    .category_list {
        height: calc(100% - 175px);
        overflow-y: auto;
        overflow-x: none;
        margin-top: 10px;
        padding: 15px;
        background: #fff;
    }

    .category_list .category_item {
        width: 100%;
        padding: 10px;
        display: inline-flex;
    }

    .category_list .category_item span {
        width: calc(100% - 40px)
    }

    .category_list .category_item div {
        width: 40px;
        cursor: pointer;
    }

    .category_list .category_item div svg {
        font-size: 18px;
    }

    .category_list .category_item a {
        color: #666;
        width: 100%;
        display: block;
        font-size: 15px;
    }

    .category_title {
        display: inline-flex;
        padding-left: 7px;
        margin-bottom: 10px;
    }

    .category_title .icon {
        width: 30px;
    }

    .category_title .icon svg {
        font-size: 20px;
    }

    .category_title .title {
        width: calc(100% - 30px);
    }

    .category_title .title a {
        color: #666;
        font-weight: 600;
        font-size: 16px;
    }

    .category_list::-webkit-scrollbar {
        width: 9px;
        height: 9px;
    }

    .category_list::-webkit-scrollbar-thumb {
        background: linear-gradient(13deg, #48cfad 14%, #48cfad 64%);
        border-radius: 10px;
    }

    .category_list::-webkit-scrollbar-thumb:hover {
        background: linear-gradient(13deg, #48cfad 14%, #48cfad 64%);
    }

    .category_list::-webkit-scrollbar-track {
        background: #eee;
        border-radius: 10px;
    }

    #subcategory,
    #subcategory .category_children {
        display: none;
    }

    .subcategory_item {
        padding: 8px 10px;
        width: 100%;
    }

    .subcategory_item a {
        color: #666;
    }

    #mnn_menu {
        position: fixed;
        z-index: 99999999;
        background: rgba(0, 0, 0, 0.35);
        width: 100%;
        height: 100%;
        left: 0;
        top: 0;
        display: none;
    }

    .page-wrapper .page-header .header.content .block-search .field.search .control .input-text {
        border-radius: 100px;
        border: none;
    }
</style>










<?php

/**
 * Copyright © 2016 Magento. All rights reserved.
 * See COPYING.txt for license details.
 */
// @codingStandardsIgnoreFile
?>
<?php
/**
 * Top menu for store
 *
 * @see \Magento\Theme\Block\Html\Topmenu
 */
?>
<?php $columnsLimit = $block->getColumnsLimit() ?: 0; ?>
<?php $_menu = $block->getHtml('level-top', 'submenu', $columnsLimit) ?>
<?php
$helper = $this->helper('Hidden\ShopkartLite\Helper\Data');
$baseUrl = $helper->getBaseUrl();
$ishome = $helper->getIsHome();

$showHome = $helper->getConfigValue('shopkartlitesettings/navigation_settings/enable');
?>

<style>
    .navigation span {
        font-weight: 400;
    }

    .navigation .nav-5 {
        float: right;
    }

    .navigation .nav-1 {
        margin-right: 20px;
    }

    .navigation .nav-1 span {
        font-weight: 500;
    }

    .nav-sections,
    .nav-sections-item-content,
    .nav-sections-item-content .ui-menu,
    .nav-sections-item-content .ui-menu li {
        height: 43px !important;
    }

    .nav-sections-item-content .ui-menu li a {
        height: 40px !important;
    }

    .nav-sections .navigation>ul>li.level0>a.level-top {
        font-size: 16px;
        margin-top: -2px;
        background: transparent !important
    }

    .nav-sections-item-content .ui-menu li a span {
        text-transform: initial;
    }

    .navigation .level0>.level-top {
        line-height: 12px;
        cursor: pointer;
    }
</style>

<nav class="navigation" role="navigation">
    <ul id="ui-id-1" class="ui-menu ui-widget ui-widget-content ui-corner-all" role="menu" tabindex="0" aria-activedescendant="ui-id-2">
        <li onclick="showCategoryMenu()" class="level0 nav-1 category-item first level-top ui-menu-item" role="presentation">
            <a class="level-top ui-corner-all" id="ui-id-2" tabindex="-1" role="menuitem">
                <i class="fa fa-bars" aria-hidden="true"></i>
                <span>Departamentos</span>
            </a>
        </li>

        <li class="level0 nav-2 category-item first level-top ui-menu-item" role="presentation">
            <a href="/" class="level-top ui-corner-all" id="ui-id-2" tabindex="-1" role="menuitem">
                <span>Início</span>
            </a>
        </li>
        <li class="level0 nav-3 category-item first level-top ui-menu-item" role="presentation">
            <a href="/wishlist" class="level-top ui-corner-all" id="ui-id-2" tabindex="-1" role="menuitem">
                <span>Lista de Compras</span>
            </a>
        </li>
        <li class="level0 nav-4 category-item first level-top ui-menu-item" role="presentation">
            <a href="/contact" class="level-top ui-corner-all" id="ui-id-2" tabindex="-1" role="menuitem">
                <span>Fale Conosco</span>
            </a>
        </li>

        <li class="level0 nav-5 category-item first level-top ui-menu-item" role="presentation">
            <a class="level-top ui-corner-all" id="ui-id-2" tabindex="-1" role="menuitem">
                <span>Comprando em Cascavel/PR</span>
            </a>
        </li>
    </ul>
</nav>