<style>
    .modal-backdrop {
        display: none;
    }

    .slide {
        background: #f9f9f9;
        border: 1px solid #dbdbdb;
        padding: 10px 15px;
        margin: 7px 0;
        display: flex;
        width: 610px;
        border-radius: 3px;
        cursor: move;
    }

    .slide_type {
        width: 170px;
    }

    .slide_name {
        width: 300px;
    }

    .slide_status {
        width: 110px;
        font-style: italic;
        opacity: 0.5;
    }

    .banner {
        background: #ffe6d1;
        border: 1px solid #ff7600;
        color: #ff7600;
        padding: 0px 10px 1px 10px;
        border-radius: 4px;
        text-align: center;
        width: 150px;
        margin-right: 15px;
    }

    .product {
        background: #d2ecff;
        border: 1px solid #0095ff;
        color: #0095ff;
        padding: 0px 10px 1px 10px;
        border-radius: 4px;
        text-align: center;
        width: 150px;
        margin-right: 15px;
    }

    .title {
        margin-top: 50px;
        font-size: 20px;
        border-bottom: 1px solid #ddd;
        margin-bottom: 4px;
        padding-bottom: 4px;
        font-weight: 600;
        color: #666;
    }

    .btn-save {
        background: #174a6f;
        border: none;
        color: #fff;
        padding: 7px 29px 8px 29px;
        transition: 0.3s;
    }

    .btn-save:hover {
        background: #1d567f;
        transition: 0.3s;
        color: #fff;
    }

    .slide_img {
        display: flex;
    }

    .slide_img input {
        border: 1px solid #ddd;
        margin-left: 10px;
        border-radius: 4px;
        width: 326px;
        font-size: 12.5px;
    }

    .header-layout {
        display: inline-flex;
        width: 850px;
        border: 1px solid #ddd;
        border-radius: 4px;
    }

    .header-item {
        width: 25%;
        height: 50px;
        background: #eee;
        cursor: move;
        float: left;
        text-align: center;
        font-weight: 600;
        padding-top: 15px;
    }
</style>

<div class="container-fluid">
    <div><input name="form_key" type="hidden" value="<?= $this->getFormKey() ?>"></div>

    <span class="msg">*clique e arraste para ordernar os sliders.</span>

    <div>
        <div class="title">
            <span>Tela de Início / Slides</span>
        </div>
        <button onclick="saveSlide()" title="Salvar" type="button" class="btn-save">
            Salvar
        </button>
    </div>

    <div class="list-item" id="sortable1" onmouseup='jQuery("#sortable1").sortable();'>
        <?php
        $sliderCollection = $block->getSlider();

        if (count($sliderCollection)) {
            foreach ($sliderCollection as $_slider) {
        ?>
                <div class="slide" style="<?= $_slider['type'] == 'product' ? 'width: 1000px' : '' ?>">
                    <div class="slide_type <?= strtolower($_slider['type']); ?>">
                        <input type="hidden" value="<?= $_slider['id'] ?>" class="slide_id">
                        <input type="hidden" value="<?= $_slider['type'] ?>" class="slide_id type">
                        <input type="hidden" value="" class="slide_order">
                        <span><?= $_slider['type'] == 'banner' ? 'Banner Slider' : 'Product Slider' ?></span>
                    </div>
                    <div class="slide_name">
                        <span><?= $_slider['name']; ?></span>
                    </div>
                    <div class="slide_status">
                        <span><?= $_slider['status'] == '1' ? 'Habilitado' : 'Desabilitado' ?></span>
                    </div>
                    <?php
                    if ($_slider['type'] == "product") {
                    ?>
                        <div class="slide_img" title="Banner Lateral">
                            <span>Imagem: </span><input placeholder="URL" value="<?= $_slider['image']; ?>" type="text">
                        </div>
                    <?php
                    }
                    ?>
                </div>
        <?php
            }
        }
        ?>
    </div>

    <div>
        <div class="title">
            <span>Cabeçalho</span>
        </div>
        <button onclick="saveHeader()" title="Salvar" type="button" class="btn-save">
            Salvar
        </button>
    </div>

    <div class="list-item header-layout" id="sortable2" onmouseup='jQuery("#sortable2").sortable();'>
        <div class="header-item" style="background: #e1e1e1; width:8.33%">
            <input type="hidden" value="1">
            Menu
        </div>

        <div class="header-item" style="background: #e6f4ff; width:16.66%">
            <input type="hidden" value="2">
            Logo
        </div>

        <div class="header-item" style="background: #f5f5f5; width:8.33%">
            <input type="hidden" value="3">
            ||
        </div>

        <div class="header-item" style="background: #ffe6e6; width:25%">
            <input type="hidden" value="4">
            Pesquisa
        </div>

        <div class="header-item" style="background: #fffae6; width:16.66%">
            <input type="hidden" value="5">
            Carrinho
        </div>

        <div class="header-item" style="background: #ecffe6; width:16.66%">
            <input type="hidden" value="6">
            Minha Conta
        </div>

        <div class="header-item" style="background: #f5f5f5; width:8.33%">
            <input type="hidden" value="7">
            ||
        </div>
    </div>
</div>

<script>
    function saveHeader() {
        var sort = "";
        jQuery(".header-item").each(function(index) {
            sort = sort + jQuery(this).find('input').val() + ',';
        });

        jQuery.post("<?= $block->getUrl("masterprice/index/layoutheadersave"); ?>", {
                sort: sort
            },
            function(data) {
                alert('Alterado com sucesso');
            }
        )
    }

    function saveSlide() {
        order = 1;
        jQuery('.slide').each(function(index) {
            jQuery(this).find('.slide_order').val(order);

            order++;
        });

        var level = [];
        var r_slides = [];

        jQuery('.slide').each(function(index) {
            r_slides = [];

            type = jQuery(this).find('.slide_type .type').val();
            id = jQuery(this).find('.slide_id').val();
            order = jQuery(this).find('.slide_order').val();
            image = jQuery(this).find('.slide_img input').val();

            r_slides.push(type);
            r_slides.push(id);
            r_slides.push(order);
            r_slides.push(image);

            level.push(r_slides);
        });

        result = jQuery.unique(level);
        result = JSON.stringify(result);

        jQuery.post("<?= $block->getUrl("masterprice/index/layoutsave"); ?>", {
                result: result
            },
            function(data) {
                alert('Alterado com sucesso');
            }
        )
    }

    require([
        'jquery'
    ], function($, $t) {
        jQuery("#sortable1").sortable();
        setTimeout(function() {
            jQuery("#sortable1").sortable();
        }, 2000);

        jQuery("#sortable2").sortable();
        setTimeout(function() {
            jQuery("#sortable2").sortable();
        }, 2000);
    })
</script>