<div class="container">
    <div><input name="form_key" type="hidden" value="<?= $this->getFormKey() ?>"></div>

    <?php
    $objectManager = \Magento\Framework\App\ObjectManager::getInstance();
    $extensionUser = $objectManager->get('Magento\Backend\Model\Auth\Session')->getUser()->getUsername();

    if ($extensionUser == 'm2n') {
    ?>
        <div class="list">
            <div class="list-item" style="height: 560px; overflow-y: scroll;">
                <div class="main-title">Produtos</div>

                <?php
                $objectManager = \Magento\Framework\App\ObjectManager::getInstance();
                $_product_list = $objectManager->create('Magento\Catalog\Model\Product')->getCollection()
                    ->addAttributeToSelect('*')
                    ->addAttributeToFilter('export_pending', 1);

                foreach ($_product_list as $_product) {
                ?>
                    <div class="item ui-state-default pending-<?= $_product->getId() ?>">
                        <div class="query query-name">
                            <span class="product-name"><?= $_product->getName() ?></span>
                        </div>

                        <div class="query query-sku">
                            <span class="product-sku"><?= $_product->getSku() ?></span>
                        </div>

                        <div class="option">
                            <button onclick="exportProduct(<?= $_product->getId() ?>,this)" class="scalable delete btn-save  action-default scalable save primary ui-button ui-widget ui-state-default ui-corner-all ui-button-text-only" type="button">Exportar</button>
                            <button onclick="exportProductRemove(<?= $_product->getId() ?>,this)" class="scalable delete btn-delete  action-default scalable save primary ui-button ui-widget ui-state-default ui-corner-all ui-button-text-only" type="button">Remover</button>
                        </div>
                    </div>
                <?php
                }
                ?>
            </div>

            <div class="list-stores" id="sortable" style="height: 560px; overflow-y: scroll;">
                <div class="main-title">Lojas</div>

                <div class="progress-bar">
                    <div id="bar">
                        <div id="progress">
                        </div>
                    </div>

                    <input type="hidden" id="qty-sent" value="0">
                </div>

                <style>
                    .progress-bar {
                        width: 100%;
                        margin-bottom: 15px;
                        display: none;
                    }

                    #bar {
                        width: 100%;
                        height: 10px;
                        background: #ddd;
                    }

                    #progress {
                        background: #174a6f;
                        height: 10px;
                        width: 0;
                        transition: 1s;
                    }

                    .main-title {
                        font-size: 22px;
                        width: 100%;
                        border-bottom: 3px solid #174a6f;
                        margin-bottom: 15px;
                        padding-bottom: 5px;
                        font-weight: 600;
                        color: #174a6f;
                    }
                    .btn-delete {
                        width: 90px !important;
                        background: #c92828 !important;
                        margin-left: 10px;
                        border-color: #c92828 !important;
                    }
                    .item .option {
                        width: 280px !important;
                        display: flex !important;
                    }
                </style>

                <?php
                $objectManager = \Magento\Framework\App\ObjectManager::getInstance();
                $_store_list = $objectManager->create('Rdtech\Masterprice\Model\Stores')->getCollection()
                    ->addFieldToSelect('*');

                foreach ($_store_list as $_store) {
                ?>
                    <div class="item ui-state-default store-<?= $_store->getId() ?>">
                        <input type="hidden" value="<?= $_store->getUrl() ?>" class="url">
                        <input type="hidden" value="<?= $_store->getToken() ?>" class="token">
                        <input type="hidden" value="<?= $_store->getId() ?>" class="store-id">

                        <div class="query" style="width: calc(100% - 150px)">
                            <span class="store-name"><?= $_store->getName() ?></span>
                        </div>
                        <div class="query" style="width: 150px">
                            <span class="store-status"></span>
                        </div>
                    </div>                    
                <?php
                }
                ?>
            </div>
        </div>
    <?php
    } else {
    ?>
        <div>
            <span>Seu usuário não tem permissão.</span>
        </div>
    <?php
    }
    ?>

    <script>
        function exportProduct(id, btn) {
            jQuery('#qty-sent').val(0)
            jQuery('#progress').css('width', 0);
            jQuery(btn).html('Exportando...');
            jQuery(btn).css('pointer-events', 'none');
            jQuery('.list-stores .item').css('opacity', '0.6');
            jQuery('.list-item').css('opacity', '0.6');
            jQuery('.list-item').css('pointer-events', 'none');

            jQuery('.store-status').html('Pendente');

            jQuery('.list-stores .item').each(function(index) {
                jQuery('.progress-bar').show();

                token = jQuery(this).find('.token').val();
                url = jQuery(this).find('.url').val();
                store = jQuery(this).find('.store-id').val();

                jQuery.post("<?= $block->getUrl("masterprice/index/productexportsend") ?>", {
                        id: id,
                        url: url,
                        token: token,
                        store: store
                    },
                    function(data) {
                        jQuery('.store-' + data).css('opacity', '1');
                        jQuery('.store-' + data).find('.store-status').html('Concluído');
                        jQuery('#qty-sent').val(parseInt(jQuery('#qty-sent').val()) + 1);

                        progress = (jQuery('#qty-sent').val() / jQuery('.list-stores .item').length) * 100;
                        jQuery('#progress').css('width', progress + '%');

                        if (progress == 100) {
                            jQuery(btn).html('100%');
                            jQuery(btn).css('background', '#aeaeae');
                            jQuery(btn).css('border-color', '#aeaeae');

                            jQuery('.list-item').css('opacity', '1');
                            jQuery('.list-item').css('pointer-events', 'initial');
                        }
                    }
                )
            });
        }

        function exportProductRemove(id, btn) {
            jQuery.post("<?= $block->getUrl("masterprice/index/productexportremove") ?>", {
                    id: id
                },
                function(data) {
                    jQuery(btn).parent().parent().remove();
                }
            )
        }

        jQuery("#sortable").sortable();
    </script>

    <style>
        .store-name {
            font-weight: 600;
            margin-bottom: 10px;
            display: inline-block;
        }

        .list {
            width: 100%;
            display: flex;
        }

        .list-item {
            width: 55%;
            padding: 0 10px;
        }

        .list-stores {
            width: 45%;
            padding: 0 10px;
        }


        .changed {
            pointer-events: none;
            opacity: 0.3;
            filter: grayscale(1);
        }

        .item .query-name {
            width: calc(100% - 400px);
        }

        .item .query-sku {
            width: 220px;
        }

        .item .option {
            width: 180px;
        }

        .query input {
            border: 1px solid #aaa;
            width: 100%;
            padding: 4px 25px;
            border-radius: 3px;
        }

        .query select {
            border: 1px solid #aaa;
            width: 100%;
            padding: 3px 25px;
            border-radius: 3px;
            background: #fff;
        }

        .query textarea {
            max-width: 340px;
            max-height: 140px;
            border: 1px solid #aaa !important;
            padding: 3px 25px;
            border-radius: 3px !important;
            background: #fff;
            margin-top: 0 !important;
        }

        .item .option button {
            margin-top: 0px;
            display: inline-block;
        }

        .sku-error {
            display: none;
            font-size: 13px;
            font-weight: 600;
            color: #e03b3b;
        }

        .item .query {
            padding-top: 16px;
        }

        .product-name,
        .product-sku {
            font-weight: 600;
        }
        .item {
            background: #ffffff;
            border: 1px solid #d3d3d3;
            border-radius: 3px;
            min-height: 65px;
        }
    </style>