<?php

/**
 * Copyright © Magento, Inc. All rights reserved.
 * See COPYING.txt for license details.
 */

/** @var $block \Magento\Checkout\Block\Cart\Sidebar */
/** @var \Magento\Framework\View\Helper\SecureHtmlRenderer $secureRenderer */
?>

<style>

</style>

<div data-block="minicart" class="minicart-wrapper mnn-minicart">
    <label><a href="/checkout/cart/">Carrinho</a></label>
    <a class="action showcart" href="<?= $block->escapeUrl($block->getShoppingCartUrl()) ?>" data-bind="scope: 'minicart_content'">
        <span class="text"><?= $block->escapeHtml(__('My Cart')) ?></span>
        <span class="counter qty empty" data-bind="css: { empty: !!getCartParam('summary_count') == false && !isLoading() },
               blockLoader: isLoading">
            <span class="counter-number">
                <!-- ko text: getCartParam('summary_count') -->
                <!-- /ko -->
            </span>
            <span class="counter-label">
                <!-- ko if: getCartParam('summary_count') -->
                <!-- ko text: getCartParam('summary_count') -->
                <!-- /ko -->
                <!-- ko i18n: 'items' -->
                <!-- /ko -->
                <!-- /ko -->
            </span>
        </span>
        <i class="fa fa-shopping-cart"></i>
    </a>
</div>

<div data-block="minicart" class="minicart-wrapper">
    <a class="action showcart" href="<?= $block->escapeUrl($block->getShoppingCartUrl()) ?>" data-bind="scope: 'minicart_content'">
        <span class="text"><?= $block->escapeHtml(__('My Cart')) ?></span>
        <span class="counter qty empty" data-bind="css: { empty: !!getCartParam('summary_count') == false && !isLoading() },
               blockLoader: isLoading">
            <span class="counter-number">
                <!-- ko text: getCartParam('summary_count') -->
                <!-- /ko -->
            </span>
            <span class="counter-label">
                <!-- ko if: getCartParam('summary_count') -->
                <!-- ko text: getCartParam('summary_count') -->
                <!-- /ko -->
                <!-- ko i18n: 'items' -->
                <!-- /ko -->
                <!-- /ko -->
            </span>
        </span>
        <i class="fa fa-shopping-cart"></i>
    </a>
    <?php if ($block->getIsNeedToDisplaySideBar()) : ?>
        <div class="block block-minicart" data-role="dropdownDialog" data-mage-init='{"dropdownDialog":{
                "appendTo":"[data-block=minicart]",
                "triggerTarget":".showcart",
                "timeout": "2000",
                "closeOnMouseLeave": false,
                "closeOnEscape": true,
                "triggerClass":"active",
                "parentClass":"active",
                "buttons":[]}}'>
            <div id="minicart-content-wrapper" data-bind="scope: 'minicart_content'">
                <!-- ko template: getTemplate() -->
                <!-- /ko -->
            </div>
            <?= $block->getChildHtml('minicart.addons') ?>
        </div>
    <?php else : ?>
        <?php $scriptString = <<<script
            require(['jquery'], function ($) {
                $('a.action.showcart').click(function() {
                    $(document.body).trigger('processStart');
                });
            });
script;
        ?>
        <?= /* @noEscape */ $secureRenderer->renderTag('script', [], $scriptString, false); ?>
    <?php endif ?>
    <?= /* @noEscape */ $secureRenderer->renderTag('script', [], 'window.checkout = ' .
        /* @noEscape */ $block->getSerializedConfig(), false); ?>
    <script type="text/x-magento-init">
        {
        "[data-block='minicart']": {
            "Magento_Ui/js/core/app": <?= /* @noEscape */ $block->getJsLayout() ?>
        },
        "*": {
            "Magento_Ui/js/block-loader": "<?= $block->escapeJs(
                                                $block->escapeUrl($block->getViewFileUrl('images/loader-1.gif'))
                                            ) ?>"
        }
    }
    </script>
</div>

<?php
$objectManager =  \Magento\Framework\App\ObjectManager::getInstance();
$storeManager  = $objectManager->get('\Magento\Store\Model\StoreManagerInterface');
$storeID       = $storeManager->getStore()->getStoreId();
$storeCode     = $storeManager->getStore()->getCode();

$storeManagerDataList = $storeManager->getStores();
?>

<div class="store-change" onclick="showChangeStore()">
    <i class="fa fa-map-marker"></i> <span> <?= $storeManager->getStore()->getName() ?></span>
</div>

<div id="formstorecelect">
    <div class="store-select">
        <div class="slider-outer" style="max-width: 1280px; margin: auto !important;">
            <div style="margin-bottom: 0;" class="owl-button-top above-padding below-padding block widget block-new-products grid">
                <div class="page-title-main">
                    <strong role="heading" aria-level="2">Nossas Lojas</strong>
                    <button onclick="hideChangeStore()" style="z-index: 99999999; float: right; position: absolute; top: -16px; right: 0px; font-size: 25px; padding: 10px 15px; cursor: pointer;">
                        <svg style="cursor: pointer" xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink" aria-hidden="true" focusable="false" width="1em" height="1em" style="-ms-transform: rotate(360deg); -webkit-transform: rotate(360deg); transform: rotate(360deg);" preserveAspectRatio="xMidYMid meet" viewBox="0 0 24 24">
                            <g fill="none" stroke="#626262" stroke-width="2" stroke-linecap="round" stroke-linejoin="round">
                                <path d="M18 6L6 18" />
                                <path d="M6 6l12 12" />
                            </g>
                        </svg>
                    </button>
                </div>
                <div class="block-content">
                    <?php
                    foreach ($storeManagerDataList as $key => $value) :
                        $objectManager = \Magento\Framework\App\ObjectManager::getInstance();
                        $storeInfo = $objectManager->create('\Rdtech\Loja\Model\Storelocator')->getCollection()
                            ->addFieldToFilter('code', $value['code'])
                            ->getFirstItem();
                    ?>
                        <div class="store-item" id="store-<?= $value['code'] ?>" onclick="changeStore(this,'<?= $value['code'] ?>')">
                            <div class="store-title">
                                <span><?= $value['name'] ?></span>
                                <span><?= $storeInfo->getAddress() ?></span>
                            </div>
                        </div>
                    <?php
                    endforeach
                    ?>
                </div>
            </div>
        </div>
    </div>
</div>


<script>
    require([
        'jquery',
        'mage/translate',
        'mage/calendar'
    ], function($, $t) {
        jQuery(document).mouseup(function(e) {
            var container = jQuery(".store-select");

            if (!container.is(e.target) && container.has(e.target).length === 0) {
                hideChangeStore()
            }
        });
    });

    function showChangeStore() {
        jQuery('.store-widget-slider .product-slider').show();
        jQuery('.overlay').fadeIn(350);
        jQuery('#formstorecelect').fadeIn(200);
    }

    function hideChangeStore() {
        jQuery('.overlay').fadeOut(350);
        jQuery('#formstorecelect').fadeOut(200);
    }

    function changeStore(item, store) {
        jQuery('.store-card-click').addClass('store-card-disabled');
        jQuery('.store-card-click').removeClass('store-card-enabled');
        jQuery(item).find('.store-card-click').removeClass('store-card-disabled');
        jQuery(item).find('.store-card-click').addClass('store-card-enabled');

        var href = jQuery('.view-' + store).find('a').attr('href');
        window.location.href = href;
    }
</script>