<?php

/**
 * Copyright © Magento, Inc. All rights reserved.
 * See COPYING.txt for license details.
 */

// phpcs:disable Magento2.Templates.ThisInTemplate
// phpcs:disable Magento2.Files.LineLength.MaxExceeded

/** @var $block \Magento\Checkout\Block\Cart\Item\Renderer */

$_item = $block->getItem();
$product = $_item->getProduct();
$isVisibleProduct = $product->isVisibleInSiteVisibility();
/** @var \Magento\Msrp\Helper\Data $helper */
$helper = $this->helper(Magento\Msrp\Helper\Data::class);
$canApplyMsrp = $helper->isShowBeforeOrderConfirm($product) && $helper->isMinimalPriceLessMsrp($product);

$objectManager = \Magento\Framework\App\ObjectManager::getInstance();
$_product = $objectManager->get('Magento\Catalog\Api\ProductRepositoryInterface')->getById($_item->getProductId());
?>



<div class="cart item-<?= $_item->getId() ?>">
    <div class="cart-product">
        <div class="cart-img">
            <?= $block->getImage($block->getProductForThumbnail(), 'cart_page_product_thumbnail')->toHtml() ?>
        </div>
        <div class="cart-item">
            <div class="cart-item-data">
                <div class="cart-item-data_name">
                    <?php if ($block->hasProductUrl()) : ?>
                        <a href="<?= $block->escapeUrl($block->getProductUrl()) ?>"><?= $block->escapeHtml($block->getProductName()) ?></a>
                    <?php else : ?>
                        <?= $block->escapeHtml($block->getProductName()) ?>
                    <?php endif; ?>

                    <div class="cart-item-category">
                        <svg xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink" aria-hidden="true" focusable="false" width="1em" height="1em" style="-ms-transform: rotate(360deg); -webkit-transform: rotate(360deg); transform: rotate(360deg);" preserveAspectRatio="xMidYMid meet" viewBox="0 0 24 24">
                            <g fill="none" stroke="#777" stroke-width="2" stroke-linecap="round" stroke-linejoin="round">
                                <path d="M6 2L3 6v14a2 2 0 0 0 2 2h14a2 2 0 0 0 2-2V6l-3-4z" />
                                <path d="M3 6h18" />
                                <path d="M16 10a4 4 0 0 1-8 0" />
                            </g>
                        </svg>
                        <span>
                            <?php
                            $categories = $_product->getCategoryIds();
                            foreach ($categories as $category) {
                                $cat = $objectManager->create('Magento\Catalog\Model\Category')->load($category);
                                $_category_name = $cat->getName();
                            }
                            echo $_category_name;
                            ?>
                        </span>
                    </div>

                    <?php
                    $objectManager = \Magento\Framework\App\ObjectManager::getInstance();
                    $StockState = $objectManager->get('\Magento\CatalogInventory\Api\StockStateInterface');
                    $_product_qty = $StockState->getStockQty($_product->getId(), $_product->getStore()->getWebsiteId());

                    if ($_item['qty'] > $_product_qty) {
                    ?>
                        <div class="col-md-12">
                            <span style="font-weight: 500; color: #ef2121;">Quantidade indisponível</span>
                        </div>
                    <?php
                    }
                    ?>
                </div>
                <div class="cart-item-data_action">
                    <div class="item-actions">
                        <div class="actions-toolbar">
                            <?= /* @noEscape */ $block->getActions($_item) ?>
                        </div>
                    </div>
                </div>
            </div>
            <div class="cart-item-data cart-item-data_details <?= $_product->getProdutoPorPeso() ? 'cart-item-data_kg' : '' ?>">

                <div class="cart-item-data_detail preco-kg">
                    <?php
                    if ($_product->getProdutoPorPeso()) {
                        if ($_product->getSpecialPrice()) {
                    ?>
                            <div class="<?= $_product->getProdutoPorPeso() ? 'peso_classe-preco  peso_classe' : 'classe_unidade unidade-preco' ?> peso-preco col price col-price" data-th="<?= $block->escapeHtml(__('Price')) ?>">
                                <span class="label-price">Preço/<?= round($_product->getProdutoPesoUnidade(), 2) ?><?= $_product->getProdutoUnidadeMedida() ?></span>
                                <span style="font-weight: 300;font-size: 13px;color: #858585;margin-top: -1px;display: block;">R$<?= number_format($_product->getPrice(), 2, ',', '.') ?></span>
                                <span style="font-weight: 600; font-size: 18px; color: #616161; margin-top: -3px; display: inline-block;">R$<?= number_format($_product->getSpecialPrice(), 2, ',', '.') ?></span>
                            </div>
                        <?php
                        } else {
                        ?>
                            <div class="<?= $_product->getProdutoPorPeso() ? 'peso_classe-preco  peso_classe' : 'classe_unidade unidade-preco' ?> peso-preco col price col-price" data-th="<?= $block->escapeHtml(__('Price')) ?>">
                                <span class="label-price">Preço/<?= round($_product->getProdutoPesoUnidade(), 2) ?><?= $_product->getProdutoUnidadeMedida() ?></span>
                                <span style="font-weight: 600; font-size: 18px; color: #616161; margin-top: -3px; display: inline-block;">R$<?= number_format($_product->getPrice(), 2, ',', '.') ?></span>
                            </div>
                    <?php
                        }
                    }
                    ?>
                </div>
                <div class="cart-item-data_detail preco-kg">
                    <?php
                    if ($_product->getProdutoPorPeso()) {
                    ?>
                        <div style="text-align:center" class="<?= $_product->getProdutoPorPeso() ? 'peso_classe-qtdpeso  peso_classe' : 'classe_unidade' ?> peso-qtd col price col-price" data-th="<?= $block->escapeHtml(__('Price')) ?>">
                            <span class="label-price">Quantidade</span>
                            <span style="font-weight: 600; font-size: 18px; color: #616161; margin-top: -3px; display: inline-block;"><?= ($block->getQty() * $_product->getProdutoPesoUnidade()) ?><?= $_product->getProdutoUnidadeMedida() ?></span>
                        </div>
                    <?php
                    }
                    ?>
                </div>
                <div class="cart-item-data_detail">
                    <div class="<?= $_product->getProdutoPorPeso() ? 'peso_classe-precokg  peso_classe' : 'classe_unidade unidade-preco' ?> col price col-price" data-th="<?= $block->escapeHtml(__('Price')) ?>">

                        <?php
                        if ($_product->getProdutoPorPeso()) {
                            if ($_product->getSpecialPrice()) {
                        ?>
                                <span class="label-price">Preço/KG</span>
                                <span style="font-weight: 300;font-size: 13px;color: #858585;margin-top: -1px;display: block;">R$<?= number_format($_product->getPriceQuilo(), 2, ',', '.') ?></span>
                                <span style="font-weight: 600; font-size: 18px; color: #616161; margin-top: -3px; display: inline-block;">R$<?= number_format($_product->getSpecialPriceQuilo(), 2, ',', '.') ?></span>
                            <?php
                            } else {
                            ?>
                                <span class="label-price">Preço/KG</span>
                                <span style="font-weight: 600; font-size: 18px; color: #616161; margin-top: -3px; display: inline-block;">R$<?= number_format($_product->getPriceQuilo(), 2, ',', '.') ?></span>
                            <?php
                            }
                        } else {
                            ?>
                            <span class="label-price">Unitário</span>
                            <?= $block->getUnitPriceHtml($_item) ?>
                        <?php
                        }
                        ?>
                    </div>
                </div>
                <div class="cart-item-data_detail">
                    <div class="<?= $_product->getProdutoPorPeso() ? 'peso_classe-qtd  peso_classe' : 'classe_unidade unidade-qtd' ?> col qty col-qty" data-th="<?= $block->escapeHtml(__('Qty')) ?>">

                        <?php
                        if ($_product->getProdutoPorPeso()) {
                        ?>
                            <span class="label-price">Qtd/<?= round($_product->getProdutoPesoUnidade(), 2) ?><?= $_product->getProdutoUnidadeMedida() ?></span>

                            <div class="field qty">
                                <div class="control qty">
                                    <label for="cart-<?= $block->escapeHtmlAttr($_item->getId()) ?>-qty">
                                        <span class="label"><?= $block->escapeHtml(__('Qty')) ?></span>
                                        <input type="hidden" class="item-id" value="<?= $block->escapeHtmlAttr($_item->getId()) ?>">
                                        <input style="height: 22px;" id="cart-<?= $block->escapeHtmlAttr($_item->getId()) ?>-qty" name="cart[<?= $block->escapeHtmlAttr($_item->getId()) ?>][qty]" data-cart-item-id="<?= $block->escapeHtmlAttr($_item->getSku()) ?>" value="<?= $block->escapeHtmlAttr($block->getQty()) ?>" type="number" size="4" step="any" title="<?= $block->escapeHtmlAttr(__('Qty')) ?>" class="input-text qty input-cart-qty" data-validate="{required:true,'validate-greater-than-zero':true}" data-role="cart-item-qty" />
                                    </label>
                                </div>
                            </div>
                        <?php
                        } else {
                        ?>
                            <span class="label-price">Qtd</span>

                            <div class="field qty">
                                <div class="control qty">
                                    <label for="cart-<?= $block->escapeHtmlAttr($_item->getId()) ?>-qty">
                                        <span class="label"><?= $block->escapeHtml(__('Qty')) ?></span>
                                        <input type="hidden" class="item-id" value="<?= $block->escapeHtmlAttr($_item->getId()) ?>">
                                        <input style="height: 22px;" id="cart-<?= $block->escapeHtmlAttr($_item->getId()) ?>-qty" name="cart[<?= $block->escapeHtmlAttr($_item->getId()) ?>][qty]" data-cart-item-id="<?= $block->escapeHtmlAttr($_item->getSku()) ?>" value="<?= $block->escapeHtmlAttr($block->getQty()) ?>" type="number" size="4" step="any" title="<?= $block->escapeHtmlAttr(__('Qty')) ?>" class="input-text qty input-cart-qty" data-validate="{required:true,'validate-greater-than-zero':true}" data-role="cart-item-qty" />
                                    </label>
                                </div>
                            </div>
                        <?php
                        }
                        ?>
                    </div>
                </div>
                <div class="cart-item-data_detail">
                    <div class="<?= $_product->getProdutoPorPeso() ? 'peso_classe-total  peso_classe' : 'classe_unidade unidade-total' ?> col col-subtotal subtotal" data-th="<?= $block->escapeHtml(__('Subtotal')) ?>">
                        <span class="label-price">Total</span>

                        <?php
                        if ($_product->getSpecialPrice()) {
                        ?>
                            <span style="font-weight: 300;font-size: 13px;color: #858585;margin-top: -1px;display: block;">R$<?= number_format($_product->getPrice() * $block->getQty(), 2, ',', '.') ?></span>
                        <?php
                        }
                        ?>

                        <?php if ($canApplyMsrp) : ?>
                            <span class="cart msrp subtotal">--</span>
                        <?php else : ?>
                            <?= $block->getRowTotalHtml($_item) ?>
                        <?php endif; ?>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>