<?php

/**
 *
 * Edit customer register template
 *
 *
 * NOTICE OF LICENSE
 *
 * @category   SystemCode
 * @package    Systemcode_BrazilCustomerAttributes
 * @author     Eduardo Diogo Dias <contato@systemcode.com.br>
 * @copyright  System Code LTDA-ME
 * @license    http://opensource.org/licenses/osl-3.0.php
 */
?>
<?php
/** @var \Magento\Customer\Block\Form\Register $block */
?>
<?php
/**
 * Create account form template
 *
 * @var $block \Magento\Customer\Block\Form\Register
 */
?>

<script>
    require([
        'jquery'
    ], function($, $t) {
        jQuery(document).ready(function() {
            jQuery('.menu .menu__border').show();
            jQuery('.menu__item').removeClass('active');
            jQuery('.menu-mobile-account').addClass('active');
            jQuery('.menu-mobile-account').click();
        })
    })
</script>

<style>
    .actions-toolbar .hidden-createaccount button:hover,
    .actions-toolbar .hidden-createaccount button {
        background: #dbdbdb !important;
        border: 1px solid #dbdbdb !important;
        color: #ffffff !important;
        cursor: not-allowed;
        pointer-events: none;
    }

    .pass_diff {
        color: #e02b27;
        font-size: 1.2rem;
        margin-top: 5px;
        display: none;
    }

    .g-recaptcha {
        display: none
    }
</style>

<?php echo $block->getChildHtml('form_fields_before') ?>
<?php /* Extensions placeholder */ ?>
<?php echo $block->getChildHtml('customer.form.register.extra') ?>
<form class="form create account form-create-account" action="<?php /* @escapeNotVerified */ echo $block->getPostActionUrl() ?>" method="post" id="form-validate" enctype="multipart/form-data" autocomplete="off">
    <?php echo $block->getBlockHtml('formkey'); ?>
    <fieldset class="fieldset create info">
        <legend class="legend"><span><?php /* @escapeNotVerified */ echo __('Personal Information') ?></span></legend><br>
        <input type="hidden" name="success_url" value="<?php /* @escapeNotVerified */ echo $block->getSuccessUrl() ?>">
        <input type="hidden" name="error_url" value="<?php /* @escapeNotVerified */ echo $block->getErrorUrl() ?>">

        <?php $_persontype = $block->getLayout()->createBlock('SystemCode\BrazilCustomerAttributes\Block\Magento\Customer\Widget\Persontype')->setTemplate('SystemCode_BrazilCustomerAttributes::widget/persontypetoggle.phtml') ?>
        <?php if ($_persontype->getConfigAdmin("general", "enabled")) : ?>
            <?php echo $_persontype->toHtml() ?>
        <?php endif ?>

        <?php echo $block->getLayout()->createBlock('Magento\Customer\Block\Widget\Name')->setObject($block->getFormData())->setForceUseCustomerAttributes(true)->toHtml() ?>

        <?php $_persontype = $block->getLayout()->createBlock('SystemCode\BrazilCustomerAttributes\Block\Magento\Customer\Widget\Persontype')->setTemplate('SystemCode_BrazilCustomerAttributes::widget/persontypefields.phtml') ?>
        <?php if ($_persontype->getConfigAdmin("general", "enabled")) : ?>
            <?php echo $_persontype->toHtml() ?>
        <?php endif ?>


        <!--
        <?php if ($block->isNewsletterEnabled()) : ?>
            <div class="field choice newsletter">
                <input type="checkbox" name="is_subscribed" title="<?php /* @escapeNotVerified */ echo __('Sign Up for Newsletter') ?>" value="1" id="is_subscribed"<?php if ($block->getFormData()->getIsSubscribed()) : ?> checked="checked"<?php endif; ?> class="checkbox">
                <label for="is_subscribed" class="label"><span><?php /* @escapeNotVerified */ echo __('Sign Up for Newsletter') ?></span></label>
            </div>
            <?php /* Extensions placeholder */ ?>
            <?php echo $block->getChildHtml('customer.form.register.newsletter') ?>
        <?php endif ?>
        -->

        <?php $_dob = $block->getLayout()->createBlock('Magento\Customer\Block\Widget\Dob') ?>
        <?php if ($_dob->isEnabled()) : ?>
            <?php echo $_dob->setDate($block->getFormData()->getDob())->toHtml() ?>
        <?php endif ?>

        <?php $_taxvat = $block->getLayout()->createBlock('Magento\Customer\Block\Widget\Taxvat') ?>
        <?php if ($_taxvat->isEnabled()) : ?>
            <?php echo $_taxvat->setTaxvat($block->getFormData()->getTaxvat())->toHtml() ?>
        <?php endif ?>

        <?php $_gender = $block->getLayout()->createBlock('Magento\Customer\Block\Widget\Gender') ?>
        <?php if ($_gender->isEnabled()) : ?>
            <?php echo $_gender->setGender($block->getFormData()->getGender())->toHtml() ?>
        <?php endif ?>
    </fieldset>

    <fieldset class="fieldset address">
        <legend class="legend"><span><?php /* @escapeNotVerified */ echo __('Address Information') ?></span></legend><br>
        <input type="hidden" name="create_address" value="1" />

        <div class="field zip required">
            <label for="zip" class="label"><span><?php /* @escapeNotVerified */ echo __('Zip/Postal Code') ?></span></label>
            <div class="control">
                <input onkeyup="buscaCep()" type="text" id="postcode" name="postcode" value="<?php echo $block->escapeHtml($block->getFormData()->getPostcode()) ?>" title="<?php /* @escapeNotVerified */ echo __('Zip/Postal Code') ?>" id="zip" class="input-text validate-zip-international <?php /* @escapeNotVerified */ echo $this->helper('Magento\Customer\Helper\Address')->getAttributeValidationClass('postcode') ?>">
            </div>
        </div>

        <?php echo $block->getLayout()->createBlock('SystemCode\BrazilCustomerAttributes\Block\Magento\Customer\Widget\StreetprefixRegister')->toHtml() ?>
        <?php echo $block->getLayout()->createBlock('SystemCode\BrazilCustomerAttributes\Block\Magento\Customer\Widget\Street')->toHtml() ?>

        <div class="field required">
            <label for="city" class="label"><span><?php /* @escapeNotVerified */ echo __('City') ?></span></label>
            <div class="control">
                <input type="text" name="city" value="<?php echo $block->escapeHtml($block->getFormData()->getCity()) ?>" title="<?php /* @escapeNotVerified */ echo __('City') ?>" class="input-text <?php /* @escapeNotVerified */ echo $this->helper('Magento\Customer\Helper\Address')->getAttributeValidationClass('city') ?>" id="city">
            </div>
        </div>

        <div class="field region required">
            <label for="region_id" class="label"><span><?php /* @escapeNotVerified */ echo __('State/Province') ?></span></label>
            <div class="control">
                <select id="region_id" name="region_id" title="<?php /* @escapeNotVerified */ echo __('State/Province') ?>" class="validate-select" style="display:none;">
                    <option value=""><?php /* @escapeNotVerified */ echo __('Please select a region, state or province.') ?></option>
                </select>
                <input type="text" id="region" name="region" value="<?php echo $block->escapeHtml($block->getRegion()) ?>" title="<?php /* @escapeNotVerified */ echo __('State/Province') ?>" class="input-text <?php /* @escapeNotVerified */ echo $this->helper('Magento\Customer\Helper\Address')->getAttributeValidationClass('region') ?>" style="display:none;">
            </div>
        </div>

        <div class="field country required">
            <label for="country" class="label"><span><?php /* @escapeNotVerified */ echo __('Country') ?></span></label>
            <div class="control">
                <?php echo $block->getCountryHtmlSelect() ?>
            </div>
        </div>
        <?php $addressAttributes = $block->getChildBlock('customer_form_address_user_attributes'); ?>
        <?php if ($addressAttributes) : ?>
            <?php $addressAttributes->setEntityType('customer_address'); ?>
            <?php $addressAttributes->setFieldIdFormat('address:%1$s')->setFieldNameFormat('address[%1$s]'); ?>
            <?php $block->restoreSessionData($addressAttributes->getMetadataForm(), 'address'); ?>
            <?php echo $addressAttributes->setShowContainer(false)->toHtml() ?>
        <?php endif; ?>

        <!--
            <div class="field company">
                <label for="company" class="label"><span><?php /* @escapeNotVerified */ echo __('Company') ?></span></label>
                <div class="control">
                    <input type="text" name="company" id="company" value="<?php echo $block->escapeHtml($block->getFormData()->getCompany()) ?>" title="<?php /* @escapeNotVerified */ echo __('Company') ?>" class="input-text <?php /* @escapeNotVerified */ echo $this->helper('Magento\Customer\Helper\Address')->getAttributeValidationClass('company') ?>">
                </div>
            </div>
             -->
        <div class="field telephone required">
            <label for="telephone" class="label"><span><?php /* @escapeNotVerified */ echo __('Phone Number') ?></span></label>
            <div class="control">
                <input type="text" name="telephone" id="telephone" value="<?php echo $block->escapeHtml($block->getFormData()->getTelephone()) ?>" title="<?php /* @escapeNotVerified */ echo __('Phone Number') ?>" class="input-text <?php /* @escapeNotVerified */ echo $this->helper('Magento\Customer\Helper\Address')->getAttributeValidationClass('telephone') ?>">
            </div>
        </div>


        <input type="hidden" name="default_billing" value="1">
        <input type="hidden" name="default_shipping" value="1">
    </fieldset>


    <fieldset class="fieldset create account" data-hasrequired="<?php /* @escapeNotVerified */ echo __('* Required Fields') ?>">
        <legend class="legend"><span><?php /* @escapeNotVerified */ echo __('Sign-in Information') ?></span></legend><br>
        <div class="field required">
            <label for="email_address" class="label"><span><?php /* @escapeNotVerified */ echo __('Email') ?></span></label>
            <div class="control">
                <input type="email" name="email" autocomplete="email" id="email_address" value="<?php echo $block->escapeHtml($block->getFormData()->getEmail()) ?>" title="<?php /* @escapeNotVerified */ echo __('Email') ?>" class="input-text" data-validate="{required:true, 'validate-email':true}">
            </div>
        </div>
        <div class="field password required" data-mage-init='{"passwordStrengthIndicator": {}}'>
            <label for="password" class="label"><span><?php /* @escapeNotVerified */ echo __('Password') ?></span></label>
            <div class="control">
                <input style="padding-left: 45px;" type="password" name="password" id="password" title="<?php /* @escapeNotVerified */ echo __('Password') ?>" class="input-text" data-password-min-length="<?php echo $block->escapeHtml($block->getMinimumPasswordLength()) ?>" data-password-min-character-sets="<?php echo $block->escapeHtml($block->getRequiredCharacterClassesNumber()) ?>" data-validate="{required:true, 'validate-customer-password':true}" autocomplete="off">

                <i onclick="showPassword(this)" style="position: absolute; z-index: 999; margin-top: 11px; font-size: 16px; margin-left: 15px; opacity: 0.8; cursor: pointer;" class="fa fa-eye-slash"></i>

                <div id="password-strength-meter-container" data-role="password-strength-meter">
                    <div id="password-strength-meter" class="password-strength-meter">
                        <?php /* @escapeNotVerified */ echo __('Password Strength'); ?>:
                        <span id="password-strength-meter-label" data-role="password-strength-meter-label">
                            <?php /* @escapeNotVerified */ echo __('No Password'); ?>
                        </span>
                    </div>
                </div>
            </div>
        </div>
        <div class="field confirmation required">
            <label for="password-confirmation" class="label"><span><?php /* @escapeNotVerified */ echo __('Confirm Password') ?></span></label>
            <div class="control">
                <input type="password" name="password_confirmation" title="<?php /* @escapeNotVerified */ echo __('Confirm Password') ?>" id="password-confirmation" class="input-text" data-validate="{required:true, equalTo:'#password'}" autocomplete="off">
            </div>

            <span class="pass_diff">A confirmação de senha não confere com a senha informada.</span>
        </div>
        <?php echo $block->getChildHtml('form_additional_info'); ?>
    </fieldset>
    <div class="actions-toolbar">
        <div class="primary confirm-createaccount hidden-createaccount">
            <button type="submit" class="action submit primary" title="<?php /* @escapeNotVerified */ echo __('Create an Account') ?>"><span><?php /* @escapeNotVerified */ echo __('Create an Account') ?></span></button>
        </div>
        <div class="secondary">
            <a class="action back" href="<?php echo $block->escapeUrl($block->getBackUrl()) ?>"><span><?php /* @escapeNotVerified */ echo __('Back') ?></span></a>
        </div>
    </div>
</form>

<?php
$objectManager =  \Magento\Framework\App\ObjectManager::getInstance();
$_tokenCep = $objectManager->get('Magento\Framework\App\Config\ScopeConfigInterface')->getValue('mnnmain/mnngeneral/tokencep');
?>

<script>
    function buscaCep() {
        cep = jQuery('#postcode').val();

        cep_verify = cep.replace("-", "");

        if (cep_verify.length >= 8) {
            cep = cep.replace("-", "");

            cep1 = cep.substr(0, 5);
            cep2 = cep.substr(5, 3);
            cepfinal = cep1 + '-' + cep2;

            require(['jquery'], function() {                        
                jQuery.post("https://mercadonanuvem.com/cep.php", {
                        codigopostal: cepfinal,
                        token: "<?= $_tokenCep ?>"
                    },
                    function(response) {
                        data = jQuery.parseJSON(response);
                        var data = JSON.parse(response);

                        data.forEach(function(cep, index) {
                            bairro = cep.bairro;
                            logradouro = cep.logradouro;
                            cidade = cep.cidade;
                            uf = cep.uf;
                        });

                        jQuery('#street_1').val(logradouro);
                        jQuery('#street_3').val(bairro);
                        jQuery('#city').val(cidade);
                        jQuery('#region_id').last().val(defineEstado(uf));

                        jQuery('#street_1').last().change()
                        jQuery('#street_3').last().change()
                        jQuery('#city').last().change()
                        jQuery('#region_id').last().change()
                    }
                )                
            });
        }
    }

    function showPassword(icon) {
        jQuery(icon).toggleClass('fa-eye');
        jQuery(icon).toggleClass('fa-eye-slash');

        var x = document.getElementById("password");
        if (x.type === "password") {
            x.type = "text";
        } else {
            x.type = "password";
        }
    }

    require([
        'jquery',
        'mage/mage'
    ], function($) {

        function PasswordConfirm() {
            jQuery("#password-confirmation").keyup(function() {
                var pass = jQuery("#password").val();
                var pass_confirm = jQuery(this).val();

                if ((pass == pass_confirm) && (!jQuery("#password-strength-meter-container").hasClass("password-weak"))) {
                    jQuery(".confirm-createaccount").removeClass("hidden-createaccount");
                    jQuery(".g-recaptcha").show();
                } else {
                    jQuery(".confirm-createaccount").addClass("hidden-createaccount");
                    jQuery(".g-recaptcha").hide();
                }

                if ((pass != pass_confirm) && (!jQuery("#password-strength-meter-container").hasClass("password-weak"))) {
                    jQuery('.pass_diff').show();
                    jQuery(".g-recaptcha").hide();
                } else {
                    jQuery('.pass_diff').hide();
                    jQuery(".g-recaptcha").show();
                }
            });
        }

        PasswordConfirm();

        jQuery('#street_2').parent().prepend('<label style="margin-bottom: 7px;display: block;" for="street_2" class="label"><span style="font-weight: 600;">Número</span> <span style="color: #e02b27;">*</span></label>')

        jQuery('#street_4').parent().prepend('<label style="margin-bottom: 7px;display: block;margin-top: -22px;" for="street_4" class="label"><span style="font-weight: 600;">Complemento</span></label>')

        var dataForm = $('#form-validate');
        var ignore = <?php /* @escapeNotVerified */ echo $_dob->isEnabled() ? '\'input[id$="full"]\'' : 'null'; ?>;

        dataForm.mage('validation', {
            <?php if ($_dob->isEnabled()) : ?>
                errorPlacement: function(error, element) {
                    if (element.prop('id').search('full') !== -1) {
                        var dobElement = $(element).parents('.customer-dob'),
                            errorClass = error.prop('class');
                        error.insertAfter(element.parent());
                        dobElement.find('.validate-custom').addClass(errorClass)
                            .after('<div class="' + errorClass + '"></div>');
                    } else {
                        error.insertAfter(element);
                    }
                },
                ignore: ':hidden:not(' + ignore + ')'
            <?php else : ?>
                ignore: ignore ? ':hidden:not(' + ignore + ')' : ':hidden'
            <?php endif ?>
        }).find('input:text').attr('autocomplete', 'off');
    });

    function defineEstado(uf) {
        switch (uf.toUpperCase()) {
            case "AC":
                data = "485";
                break;
            case "AL":
                data = "486";
                break;
            case "AP":
                data = "487";
                break;
            case "AM":
                data = "488";
                break;
            case "BA":
                data = "489";
                break;
            case "CE":
                data = "490";
                break;
            case "ES":
                data = "491";
                break;
            case "GO":
                data = "492";
                break;
            case "MA":
                data = "493";
                break;
            case "MG":
                data = "496";
                break;
            case "MS":
                data = "495";
                break;
            case "MT":
                data = "494";
                break;
            case "PA":
                data = "497";
                break;
            case "PB":
                data = "498";
                break;
            case "PR":
                data = "499";
                break;
            case "PE":
                data = "500";
                break;
            case "PI":
                data = "501";
                break;
            case "RJ":
                data = "502";
                break;
            case "RN":
                data = "503";
                break;
            case "RS":
                data = "504";
                break;
            case "RO":
                data = "505";
                break;
            case "RR":
                data = "506";
                break;
            case "SC":
                data = "507";
                break;
            case "SP":
                data = "508";
                break;
            case "SE":
                data = "509";
                break;
            case "TO":
                data = "510";
                break;
            case "DF":
                data = "511";
                break;
        }

        return data;
    }
</script>

<script type="text/x-magento-init">
    {
        "#country": {
            "regionUpdater": {
                "optionalRegionAllowed": <?php /* @escapeNotVerified */ echo ($block->getConfig('general/region/display_all') ? 'true' : 'false'); ?>,
                "regionListId": "#region_id",
                "regionInputId": "#region",
                "postcodeId": "#zip",
                "form": "#form-validate",
                "regionJson": <?php /* @escapeNotVerified */ echo $this->helper('Magento\Directory\Helper\Data')->getRegionJson() ?>,
                "defaultRegion": "<?php /* @escapeNotVerified */ echo $block->getFormData()->getRegionId() ?>",
                "countriesWithOptionalZip": <?php /* @escapeNotVerified */ echo $this->helper('Magento\Directory\Helper\Data')->getCountriesWithOptionalZip(true) ?>
            }
        }
    }
</script>